-- =========== Directorio de Servicios: "Cantones de costarica" =========== --
-- ========================== Utilizando MySQL ============================ --

USE DIRECTORIO_SERVICIOS;

-- San José --
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'San José');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Escazú');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Desamparados');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Puriscal');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Tarrazú');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Aserrí');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Mora');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Goicoechea');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Santa Ana');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Alajuelita');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Vásquez de Coronado');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Acosta');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Tibás');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Moravia');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Montes de Oca');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Turrubares');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Dota');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Curridabat');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'Pérez Zeledón');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('San José', 'León Cortés Castro');

-- Alajuela --
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Alajuela');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'San Ramón');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Grecia');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'San Mateo');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Atenas');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Naranjo');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Palmares');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Poás');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Orotina');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'San Carlos');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Zarcero');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Valverde Vega');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Upala');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Los Chiles');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Guatuso');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Alajuela', 'Río Cuarto');

-- Cartago --
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Cartago', 'Cartago');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Cartago', 'Paraíso');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Cartago', 'La Unión');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Cartago', 'Jiménez');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Cartago', 'Turrialba');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Cartago', 'Alvarado');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Cartago', 'Oreamuno');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Cartago', 'El Guarco');

-- Heredia --
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'Heredia');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'Barva');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'Santo Domingo');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'Santa Bárbara');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'San Rafael');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'San Isidro');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'Belén');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'Flores');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'San Pablo');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Heredia', 'Sarapiquí');

-- Guanacaste --
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Liberia');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Nicoya');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Santa Cruz');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Bagaces');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Carrillo');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Cañas');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Abangares');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Tilarán');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Nandayure');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'La Cruz');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Guanacaste', 'Hojancha');

-- Puntarenas -- 
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Puntarenas');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Esparza');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Buenos Aires');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Montes de Oro');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Osa');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Quepos');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Golfito');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Coto Brus');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Parrita');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Corredores');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Puntarenas', 'Garabito');

-- Limón --
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Limón', 'Limón');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Limón', 'Pococí');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Limón', 'Siquirres');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Limón', 'Talamanca');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Limón', 'Matina');
INSERT INTO UBICACIONES (PROVINCIA, CANTON)
VALUES ('Limón', 'Guácimo');

