-- =========== Directorio de Servicios: "IMPLEMENTACION DE LA BASE DE DATOS =========== --
-- ================================= Utilizando MySQL ================================= --

CREATE DATABASE TEST;

USE TEST;

-- ===========================TABLA "CLIENTES"=========================== --
/*
Almacena los clientes
*/
CREATE TABLE CLIENTES (
	ID_CLIENTE INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT, -- SOLO POSITIVOS
	NOMBRE_CLIENTE VARCHAR(20) NOT NULL,
	APELLIDO1_CLIENTE VARCHAR(20) NOT NULL,
	APELLIDO2_CLIENTE VARCHAR(20),
    CORREO_CLIENTE VARCHAR(30) UNIQUE NOT NULL, -- EL CORREO NO SE REPITE
    TELEFONO_CLEINTE VARCHAR(8),
    
	BORRADO_CLIENTE BIT DEFAULT 0 NOT NULL
);


-- ===========================TABLA "PROFESIONALES"=========================== --
/*
Almacena los profecionales
*/
CREATE TABLE PROFECIONALES (
	ID_PROFECIONAL INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT, -- SOLO POSITIVOS
	NOMBRE_PROFECIONAL VARCHAR(20) NOT NULL,
	APELLIDO1_PROFECIONAL VARCHAR(20) NOT NULL,
	APELLIDO2_PROFECIONAL VARCHAR(20),
    CORREO_PROFECIONAL VARCHAR(30) UNIQUE NOT NULL, -- EL CORREO NO SE REPITE
    TELEFONO_PROFECIONAL VARCHAR(8),
    
    DESCRIPCION VARCHAR(200),
    CALIFIC_CONTADOR INT UNSIGNED,		-- CUENTA LAS CALIFICACIONES
    CALIFIC_SUMA INT UNSIGNED,			-- SUMA DE LAS CALIFICACIONES
    
	BORRADO_PROFECIONAL BIT DEFAULT 0 NOT NULL
);

-- ===========================TABLA "CALIFICACIONES"=========================== --
/*
Almacena las calificaciones que los clientes le dieron a los profecionales
tambien contiene los comentarios y la fecha en que se hicieron

los clientes solo pueden calificar a los profecionales una vez
*/
CREATE TABLE CALIFICACIONES (
	ID_CLIENTE INTEGER UNSIGNED,
    ID_PROFECIONAL INTEGER UNSIGNED,
	CALIFICACION DECIMAL(3,2),
    COMENTARIO VARCHAR(200),
    FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- ALMACENA LA FECHA EN QUE SE CREO
    PRIMARY KEY (ID_CLIENTE, ID_PROFECIONAL)
);
ALTER TABLE CALIFICACIONES ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE);
ALTER TABLE CALIFICACIONES ADD FOREIGN KEY (ID_PROFECIONAL) REFERENCES PROFECIONALES(ID_PROFECIONAL);

-- ===========================TABLA "OCUPACIONES"=========================== --
/*
almacena las diferentes ocupaciones
evita datos repetidos
*/
CREATE TABLE OCUPACIONES (
	ID_OCUPACION INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_OCUPACION VARCHAR(20),
	ESPACIALIDAD_OCUPACION VARCHAR(20)
);

-- ===========================TABLA "OCUPACIONES_PROFECIONALES"=========================== --
/*
asigna una o multiples ocupacione a los profecionales
*/
CREATE TABLE OCUPACIONES_PROFECIONALES (
	ID_PROFECIONAL INTEGER UNSIGNED,
	ID_OCUPACION INTEGER UNSIGNED,
    
    -- Un profecional no puede tener la misma ocupacion dos veces
    PRIMARY KEY(ID_PROFECIONAL, ID_OCUPACION)
);
ALTER TABLE OCUPACIONES_PROFECIONALES ADD FOREIGN KEY (ID_PROFECIONAL) REFERENCES PROFECIONALES(ID_PROFECIONAL);
ALTER TABLE OCUPACIONES_PROFECIONALES ADD FOREIGN KEY (ID_OCUPACION) REFERENCES OCUPACIONES(ID_OCUPACION);

-- ===========================TABLA "WEBSITES"=========================== --
/*
almacena los sitios web suministrados por el profecional
*/
CREATE TABLE WEBSITES (
    ID_PROFECIONAL INTEGER UNSIGNED,
	URL_SITIO VARCHAR(20),
    MONBRE_SITIO VARCHAR(20),
    PRIMARY KEY (ID_PROFECIONAL, URL_SITIO)
);
ALTER TABLE WEBSITES ADD FOREIGN KEY (ID_PROFECIONAL) REFERENCES PROFECIONALES(ID_PROFECIONAL);

-- ===========================TABLA "UBICACIONES"=========================== --
/*
almacena las ubicaciones
es para mantener consistencia en los datos
hay que cargar todos los cantones
*/
CREATE TABLE UBICACIONES (
	ID_UBICAION INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	PROVINCIA ENUM('San José',
					'Alajuela',
					'Cartago',
					'Heredia',
                    'Guanacaste',
					'Puntarenas',
					'Limón') NOT NULL,
    CANTON VARCHAR(20)
);

-- ===========================TABLA "OCUPACIONES_PROFECIONALES"=========================== --
/*
asigna una o multiples ubicaciones a los profecionales
*/
CREATE TABLE UBICACIONES_PROFECIONALES (
	ID_PROFECIONAL INTEGER UNSIGNED,
	ID_UBICAION INTEGER UNSIGNED,
    DETALLES VARCHAR(100), -- opcional (direccion exacta)
    
    -- Un profecional no puede tener la misma ocupacion dos veces
    PRIMARY KEY(ID_PROFECIONAL, ID_UBICAION)
);
ALTER TABLE UBICACIONES_PROFECIONALES ADD FOREIGN KEY (ID_PROFECIONAL) REFERENCES PROFECIONALES(ID_PROFECIONAL);
ALTER TABLE UBICACIONES_PROFECIONALES ADD FOREIGN KEY (ID_UBICAION) REFERENCES UBICACIONES(ID_UBICAION);

