DELIMITER $$
CREATE PROCEDURE `REGISTRAR_Y_ACTUALIZARINFO_USUARIOS`(IN _ID_USUARIOS INT,
													  IN _NOMBRE VARCHAR(20),
                                                      IN _APELLIDO1 VARCHAR(20),
                                                      IN _APELLIDO2 VARCHAR(20),
                                                      IN _CORREO VARCHAR(30),
                                                      IN _TELEFONO VARCHAR(8),
                                                      IN _DESCRIPCION varchar(500),
                                                      IN _USUARIO_PREMIUM BIT,
                                                      IN _ES_PROFESIONAL BIT)
BEGIN
	IF _ID_USUARIOS IN(SELECT ID_USUARIO FROM USUARIOS) THEN
		CASE _ES_PROFESIONAL
		WHEN 1 THEN 
        
				UPDATE USUARIOS
				SET NOMBRE_PROFESIONAL=_NOMBRE,
					APELLIDO1_PROFESIONAL=_APELLIDO1,
					APELLIDO2_PROFESIONAL=_APELLIDO2,
					CORREO_PROFESIONAL=_CORREO,
					TELEFONO_PROFESIONAL=_TELEFONO,
					DESCRIPCION=_DESCRIPCION,
					USUARIO_PREMIUM=_USUARIO_PREMIUM
				WHERE ID_USUARIO=_ID_USUARIOS;
		WHEN 0 THEN
        
			UPDATE USUARIOS
				SET NOMBRE_PROFESIONAL=_NOMBRE,
					APELLIDO1_PROFESIONAL=_APELLIDO1,
					APELLIDO2_PROFESIONAL=_APELLIDO2
				WHERE ID_USUARIO=_ID_USUARIOS;
                
		END CASE;
	ELSE 
		CASE _ES_PROFESIONAL
		WHEN 1 THEN 
        
				insert INTO USUARIOS(NOMBRE_PROFESIONAL,APELLIDO1_PROFESIONAL,APELLIDO2_PROFESIONAL,CORREO_PROFESIONAL,TELEFONO_PROFESIONAL,DESCRIPCION,USUARIO_PREMIUM,PERFIL_PROFESIONAL)
				VALUES(_NOMBRE,_APELLIDO1,_APELLIDO2,_CORREO,_TELEFONO,_DESCRIPCION,_USUARIO_PREMIUM,_ES_PROFESIONAL);
             		        SET _ID_USUARIO=last_insert_id();
		WHEN 0 THEN
        
			insert INTO USUARIOS(NOMBRE_PROFESIONAL,APELLIDO1_PROFESIONAL,APELLIDO2_PROFESIONAL,PERFIL_PROFESIONAL)
				VALUES(_NOMBRE,_APELLIDO1,_APELLIDO2,_ES_PROFESIONAL);
                
		END CASE;
	END IF;
END$$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE `INSERTAR_OCUPACION`(IN _ID_USUARIO INT,
					IN _ID_OCUPACION int,
                                      IN _msg varchar(500))
BEGIN
	if _ID_OCUPACION IN(SELECT ID_OCUPACION WHERE ID_USUARIO=_ID_USUARIO) THEN
		SET _msg='La ocupaciòn ya esta registrada con este usuario';
	else
		INSERT INTO OCUPACIONES_PROFECIONALES
       		 VALUES(_ID_USUARIO,_ID_OCUPACION);
    END IF
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `REMOVER_OCUPACION_DE_USUARIO`(IN _ID_USUARIO INT,
						IN _ID_OCUPACION int)
BEGIN
	DELETE FROM OCUPACIONES_PROFECIONALES WHERE ID_USUARIO=_ID_USUARIO AND ID_OCUPACION=_ID_OCUPACION;
END$$
DELIMITER ;
